### ISSUE TITLE
Is this a copy-paste typo?

### ISSUE THREAD

**Issue by valyard** [raspofabs/dodbooksourcecode#7]
https://github.com/raspofabs/dodbooksourcecode/blob/master/KeyLookup.cpp#L120
The var h is not used in that function and looks like a copy-paste typo. In the book, there's no context for the function, so it looks more puzzling.

**Comment by raspofabs** [comment]
Oh, well spotted. Thanks.

⁣Sent from TypeApp ​

**Comment by raspofabs** [comment]
Those two lines can be removed. They must be there from when it did a binary chop after skipping. Thank you again.

⁣Sent from TypeApp ​
